//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDNH
    {
        public int MaCTDNH { get; set; }
        public Nullable<int> MaDNH { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
    
        public virtual DonNhapHang DonNhapHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
