//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDH
    {
        public ChiTietDH()
        {
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public int MaCTDH { get; set; }
        public Nullable<int> MaDH { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> SoLuongMua { get; set; }
        public string YeuCau { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual ICollection<DanhGia> DanhGias { get; set; }
    }
}
