//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int MaDG { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaCTDH { get; set; }
        public Nullable<int> DiemDG { get; set; }
        public string BinhLuan { get; set; }
        public Nullable<System.DateTime> NgayDG { get; set; }
    
        public virtual ChiTietDH ChiTietDH { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
