//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.Anh_SanPham = new HashSet<Anh_SanPham>();
            this.ChiTietDHs = new HashSet<ChiTietDH>();
            this.ChiTietDNHs = new HashSet<ChiTietDNH>();
            this.MoTa_SanPham = new HashSet<MoTa_SanPham>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public decimal Gia { get; set; }
        public int SoLuongTon { get; set; }
        public int MaDM { get; set; }
    
        public virtual ICollection<Anh_SanPham> Anh_SanPham { get; set; }
        public virtual ICollection<ChiTietDH> ChiTietDHs { get; set; }
        public virtual ICollection<ChiTietDNH> ChiTietDNHs { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ICollection<MoTa_SanPham> MoTa_SanPham { get; set; }
    }
}
